import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
#tk._test()
frm=tk.Tk()
w=900
h=500
ws=(frm.winfo_screenwidth()-w)/2
hs=(frm.winfo_screenheight()-h)/2 - 40
frm.geometry("%dx%d+%d+%d" %(w,h,ws,hs))
frm.title("New text Document-Notepad")
txtout1 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout2 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout3 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout4 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout5 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout6 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout7 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout8 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout9 = ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout10= ttk.Combobox(frm,values=("Hello!.."," "," "),width=150,border=None)
txtout1.grid(row=0,column=0)
txtout2.grid(row=1,column=0)
txtout3.grid(row=2,column=0)
txtout4.grid(row=3,column=0)
txtout5.grid(row=4,column=0)
txtout6.grid(row=5,column=0)
txtout7.grid(row=6,column=0)
txtout8.grid(row=7,column=0)
txtout9.grid(row=8,column=0)
txtout10.grid(row=9,column=0)
def showwindow():
    f=tk.Toplevel()
    w = 900
    h = 500
    ws = (f.winfo_screenwidth() - w) / 2
    hs = (f.winfo_screenheight() - h) / 2 - 40
    f.geometry("%dx%d+%d+%d" % (w, h, ws, hs))
    f.title("Untitle-Notepad")
    f.grab_set()
menu = tk.Menu(frm)
filemen = tk.Menu(menu,tearoff=0)
filemen.add_command(label="New")
filemen.add_command(label="New Window",command=showwindow)
filemen.add_command(label="open...")
filemen.add_command(label="save")
filemen.add_command(label="save as...")
filemen.add_separator()
filemen.add_command(label="page setup...")
filemen.add_command(label="print...")
filemen.add_separator()
filemen.add_command(label="Exit",command=lambda :frm.destroy())
menu.add_cascade(label="File",menu=filemen)
editmen = tk.Menu(menu,tearoff=0)
editmen.add_command(label="undo")
editmen.add_separator()
editmen.add_command(label="cut")
editmen.add_command(label="copy")
editmen.add_command(label="paste")
editmen.add_command(label="delete")
editmen.add_separator()
editmen.add_command(label="search with Bing...")
editmen.add_command(label="find...")
editmen.add_command(label="find Next")
editmen.add_command(label="find previous")
editmen.add_command(label="Replace")
editmen.add_command(label="Go to")
editmen.add_separator()
editmen.add_command(label="Select All")
editmen.add_command(label="Time / Date")
menu.add_cascade(label="Edit",menu=editmen)
def ShowFont():
    f1= tk.Toplevel()
    pad=10
    w = 500
    h = 500
    ws = (f1.winfo_screenwidth() - w) / 2
    hs = (f1.winfo_screenheight() - h) / 2 - 40
    f1.geometry("%dx%d+%d+%d" % (w, h, ws, hs))
    f1.title("Font")
    frame1= ttk.Frame(f1)
    ttk.Label(frame1,text="Font:").grid(row=0,column=0,pady=pad,padx=6)
    ttk.Label(frame1,text="Font Style:").grid(row=0,column=1,pady=pad,padx=100)
    ttk.Label(frame1,text="Size:").grid(row=0,column=2,pady=pad,padx=10)
    frame1.pack()
    frame2 = ttk.Frame(f1)
    ttk.Entry(frame2).grid(row=0, column=0, padx=10)
    ttk.Entry(frame2).grid(row=0, column=2, padx=10)
    ttk.Entry(frame2).grid(row=0, column=3, padx=5)
    frame2.pack()
    frame3 = ttk.Frame(f1)
    listbox = tk.Listbox(frame3)
    listbox.insert(0,"malak")
    listbox.insert(1,"omar")
    listbox.insert(2,"Ahmed")
    listbox.insert(3,"Mohamed")
    listbox.insert(4,"sara")
    listbox.insert(4,"cosole")
    listbox.insert(5,"Mokhtar")
    listbox.grid(row=0,column=0)
    listbox1 = tk.Listbox(frame3)
    listbox1.insert(0, "Rugalr")
    listbox1.insert(1, "italic")
    listbox1.insert(2, "Bold")
    listbox1.insert(3, "Bold Italic")
    listbox1.insert(4, "tahoma")
    listbox1.grid(row=0,column=1,padx=25)
    listbox2 = tk.Listbox(frame3)
    listbox2.insert(0, "8")
    listbox2.insert(1, "9")
    listbox2.insert(2, "10")
    listbox2.insert(3, "11")
    listbox2.insert(4, "12")
    listbox2.insert(5, "14")
    listbox2.insert(5, "16")
    listbox2.insert(5, "18")
    listbox2.insert(5, "20")
    listbox2.insert(5, "22")
    listbox2.insert(5, "24")
    listbox2.insert(5, "26")
    listbox2.grid(row=0, column=2)
    txt=tk.Label(frame3,text="script",font=("None 15 bold"))
    txt.grid(row=1,column=1,pady=pad)
    com=ttk.Combobox(frame3,values=("westren","Asudia","UsA","Roma","Franca","Rwsea"))
    com.current(0)
    com.grid(row=2,column=1,pady=0)
    txt = tk.Menubutton(frame3,text="Show More Font",foreground="navy")
    txt.grid(row=3,column=0,pady=50)
    Btn1 = ttk.Button(frame3,text="Ok")
    Btn2 = ttk.Button(frame3,text="Cancel",command=lambda :f1.destroy())
    Btn1.grid(row=4,column=1)
    Btn2.grid(row=4,column=2)
    frame3.pack()
    f1.grab_set()
formatmen = tk.Menu(menu,tearoff=False)
formatmen.add_command(label="Word Wrap")
formatmen.add_command(label="Font...",command=ShowFont)
menu.add_cascade(label="Format",menu=formatmen)
veiwmen = tk.Menu(menu,tearoff=False)
veiwmen.add_command(label="Zoom")
veiwmen.add_command(label="Status Bar")
menu.add_cascade(label="View",menu=veiwmen)
helpmen = tk.Menu(menu,tearoff=False)
helpmen.add_command(label="View Help")
helpmen.add_command(label="Send feedBack")
helpmen.add_separator()
helpmen.add_command(label="About Notepad")
menu.add_cascade(label="Help",menu=helpmen)
frm.config(menu=menu)
frm.mainloop()
